### ISSUE TITLE
Multiple connections crash nordconn

### ISSUE THREAD

**Issue by miguelfeliciovieira** [goulov/nordconn#1]
Cannot disconnect after multiple connections, as the script returns an unexpected error:

`ERROR: NordVPN not connected, or not started with 'nordconn.sh'. OpenVPN must be killed manually.`

**Comment by goulov** [comment]
indeed the script doesn't check if you're already connected and that's why you're having problems, I'll fix this asap

**Comment by goulov** [comment]
closed in https://github.com/goulov/nordconn/commit/10d2f8145d69139dbcdda0c23e618c9ba7bad304
